# Generated by Django 4.0.4 on 2022-06-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineInfo',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('total', models.PositiveIntegerField(default=0)),
                ('left', models.PositiveIntegerField(default=0)),
                ('vaccination_dates', models.DateField()),
                ('users', models.ManyToManyField(through='vaccineBooking.VaccineBooking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vaccinebooking',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineBooking.vaccineinfo'),
        ),
    ]
